### ISSUE TITLE
Array type and optional information missing for optional array type parameters

### ISSUE THREAD

**Issue by Sanjo** [electron/docs-parser#13]
__Example:__
* [app.setAsDefaultProtocolClient(protocol[, path, args])](https://electronjs.org/docs/api/app#appsetasdefaultprotocolclientprotocol-path-args) for the `args` parameter it shows `String` instead of `String[]` and no `(optional)` label.

Other occurences can be found by searching for `[] (optional)` in the folder `docs/` inside the "electron" repository.

**Comment by MarshallOfSound** [comment]
This isn't an issue with the parser, the website is rendering the raw markdown (and getting it wrong).  I think we have this tracked somewhere but if you can't find it can you raise this as an issue on the website repo?

https://github.com/electron/electronjs.org
