### ISSUE TITLE
DX: include keyToken.content in error when keyToken.type is not `code_inline`

### ISSUE THREAD

**Issue by bnb** [electron/docs-parser#20]
Currently, when the process crashes because it encounters an unexpected list entry (?) that is not an inline code block it spits out this message:

```sh
✖ Generating API in directory: "/Users/cyren/GitHub/node-docs-parser"
An error occurred while processing: "/Users/cyren/GitHub/node-docs-parser/docs/api/v8.md"
AssertionError: Expected key token to be an inline code block: expected 'text' to equal 'code_inline'
```

The last line is the useful context, and having dug more into the code I can now pretty clearly understand what the error is asserting. However, when running this as someone not experienced with the tool, having the context of "what text is actually triggering this to happen would be super useful.

I _personally_ was able to figure out the exact context by adding `console.log(keyToken)` in the globally installed module and seeing the entry before it failed. I was able to see the specific content from `keyToken.content` which allowed me to debug my docs and solve the problem.

It would be awesome to see `keyToken.content` included in the [error message](https://github.com/electron/docs-parser/blob/master/src/markdown-helpers.ts#L671) if at all possible. One possible solution, though I don't know if it'll be properly output:

```js
    expect(keyToken.type).to.equal('code_inline', `Expected key token to be an inline code block at "${keyToken.content}"`);`
```

**Comment by MarshallOfSound** [comment]
Yeah even I had to look up the code to figure out exactly what that was complaining about 👍 Defs open to PRs to improve the error messages here

**Comment by bnb** [comment]
Closing since #22 was merged and I'm a potato who still hasn't figured out how the "Closes <issue>" feature works.
