### ISSUE TITLE
process field not read correctly

### ISSUE THREAD

**Issue by tong** [electron/docs-parser#32]
This https://github.com/electron/docs-parser/issues/14 never landed in electron project.  
The electron-api.json is still released with process fields always true.

**Comment by dsanders11** [comment]
@tong, it looks like it's correct for [v10.1.3](https://github.com/electron/electron/releases/download/v10.1.3/electron-api.json)? I think maybe for older releases `docs-parser` is not updated after that version releases, so they wouldn't have gotten the fix from #14.
