### ISSUE TITLE
Is repoUrl Useful?

### ISSUE THREAD

**Issue by dsanders11** [electron/docs-parser#70]
This comes out of #47. The `repoUrl` field in `electron-api.json` has been has broken URLs for a long time now and no one seems to have noticed. If no one is using the field, should it just be removed for simplicity? Leaving this as an open question since @ckerr brought it up on that PR review.

**Comment by MarshallOfSound** [comment]
Making a breaking change just because we're unaware of a usage of a field is not a good move IMO.  It isn't causing us any issues keeping it around.

Strong -1 on removing anything from this structure

**Comment by dsanders11** [comment]
I mostly agree, was just opening the issue to not lose the context from that PR and allow further discussion.
