### ISSUE TITLE
It seems to be impossible to document functions that are attached to a certain property

### ISSUE THREAD

**Issue by FrankenApps** [electron/docs-parser#96]
I would like to fix this [Issue](https://github.com/electron/electron/issues/10096#issuecomment-1003426383). 

Especially I would like to document the `view.webContents.destroy()` method so that I can use it from typescript without having to do shenangians like `(view.webContents as any).destroy()`.

To make it work, normally all that would be required is the change from 
```typescript
    /**
     * A `WebContents` object owned by this view.
     *
     * @experimental
     */
    webContents: WebContents;
```
to
```typescript
    /**
     * A `WebContents` object owned by this view.
     *
     * @experimental
     */
    webContents: WebContents & {
      /**
       * Destroys the `WebContents` of the associated `BrowserView`.
       *
       * @experimental
       */
      destroy(): void;
    };
```
in the typescript definition of the `BrowserView` class.

However because the typescript defintions are auto-generated form the JSON API file retrieved by parsing the documentation, it seems to me that it is impossible at the moment to make that improvement.

What would be the best option to make such edge cases work? Do we need to extend the parser and the defintions generator and then adjust the documentation somehow?

**Comment by MarshallOfSound** [comment]
This is not a supported case, APIs that aren't documented should not be typed. If you want to call unsupported and undocumented APIs you will need to do the unsafe `any` or `unknown` cast.
